from django.db import models

from Resume.models import Resume


class ResumeParserResult(models.Model):
    """
    Stores the structured output generated by ResumeParserAgent.
    """

    resume = models.OneToOneField(
        Resume,
        on_delete=models.CASCADE,
        related_name="parser_result"
    )

    parsed_data = models.JSONField(
        help_text="Validated ResumeSchema output."
    )

    ai_model = models.CharField(
        max_length=100,
        default="gemini-2.5-flash"
    )

    processing_time = models.FloatField(
        default=0.0,
        help_text="Execution time in seconds."
    )

    prompt_version = models.CharField(
        max_length=20,
        default="v1"
    )

    status = models.CharField(
        max_length=20,
        choices=[
            ("SUCCESS", "Success"),
            ("FAILED", "Failed"),
        ],
        default="SUCCESS"
    )

    error_message = models.TextField(
        blank=True
    )

    created_at = models.DateTimeField(
        auto_now_add=True
    )

    updated_at = models.DateTimeField(
        auto_now=True
    )

    class Meta:
        db_table = "ai_resume_parser_result"
        ordering = ["-created_at"]
        verbose_name = "Resume Parser Result"
        verbose_name_plural = "Resume Parser Results"

    def __str__(self):
        return f"Resume #{self.resume.id} Parser Result"