from django.db import models
from Resume.models import Resume


class ResumeAnalysisResult(models.Model):
    """
    Stores the output generated by ResumeAnalysisAgent.
    """

    resume = models.OneToOneField(
        Resume,
        on_delete=models.CASCADE,
        related_name="analysis_result"
    )

    analysis_data = models.JSONField()

    created_at = models.DateTimeField(auto_now_add=True)

    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        db_table = "ResumeAnalysisResult"
        verbose_name = "Resume Analysis Result"
        verbose_name_plural = "Resume Analysis Results"

    def __str__(self):
        return f"Analysis Result - Resume {self.resume.id}"