from django.db import models

from Resume.models import Resume


class ResumeParserResult(models.Model):
    """
    Stores the structured resume generated by ResumeParserAgent.
    """

    resume = models.OneToOneField(
        Resume,
        on_delete=models.CASCADE,
        related_name="parser_result"
    )

    parsed_data = models.JSONField()

    created_at = models.DateTimeField(
        auto_now_add=True
    )

    updated_at = models.DateTimeField(
        auto_now=True
    )

    class Meta:
        db_table = "ResumeParserResult"
        ordering = ["-created_at"]
        verbose_name = "Resume Parser Result"
        verbose_name_plural = "Resume Parser Results"

    def __str__(self):
        return f"Parser Result - Resume {self.resume.id}"